### ISSUE TITLE
Spin up basic Web-server

### ISSUE THREAD

**Issue by bderiso** [bderiso/Podcast-Cleaner#2]

**Comment by finalcommand** [comment]
How do you want this website to look?

**Comment by bderiso** [comment]
Honestly, I have no preference right now. A dark background would be nice
just for my personal preference.

I'm thinking more about layout at the moment. The main page should
basically be a sales pitch and sign-up hub, and then links to podcasts we
partner with.

I'm open to suggestions.

------------------------------
Brandon L. Deriso
<http://www.linkedin.com/in/brandonderiso>
BDeriso@GMail.com
Cell: (504) 919-6681

**Comment by finalcommand** [comment]
Wordpress or Joomla backend

**Comment by bderiso** [comment]
wordpress seems like a fine option. many/most podcasters use it for their
site AND their podcast feed.


------------------------------
Brandon L. Deriso
<http://www.linkedin.com/in/brandonderiso>
BDeriso@GMail.com
Cell: (504) 919-6681

**Comment by finalcommand** [comment]
You want this on the same server? I have a web server that all it does.

**Comment by bderiso** [comment]
any server is fine for aplha. when we move to beta i'll probably grab my
own VPS unless you want to take it to prod (let me know if you want
compensation).

------------------------------
Brandon L. Deriso
<http://www.linkedin.com/in/brandonderiso>
BDeriso@GMail.com
Cell: (504) 919-6681
